# Generated by Django 5.2.3 on 2025-06-29 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='plateform_status',
            new_name='platform_status',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='techer_course_status',
            new_name='teacher_course_status',
        ),
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
