# Generated by Django 5.2.3 on 2025-06-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_plateform_status_course_platform_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
