# Generated by Django 5.2.3 on 2025-07-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_card_id_cart_cart_id_alter_course_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
