# Generated by Django 5.2.3 on 2025-07-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantitem',
            name='file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
