# Generated by Django 5.2.3 on 2025-07-18 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_variantitem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
