# Generated by Django 5.2.3 on 2025-07-18 07:02

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_variantitem_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantitem',
            name='variant',
            field=smart_selects.db_fields.ChainedForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_items', to='api.variant'),
        ),
    ]
