# Generated by Django 5.2.3 on 2025-07-18 08:02

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_variantitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='variant',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='course', chained_model_field='course', on_delete=django.db.models.deletion.CASCADE, to='api.variant'),
        ),
    ]
