# Generated by Django 5.2.3 on 2025-07-24 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='taxt_rate',
            new_name='tax_rate',
        ),
    ]
