# Generated by Django 5.2.3 on 2025-07-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_taxt_rate_country_tax_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourse',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
