# Generated by Django 5.2.3 on 2025-07-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_teacher_enrolledcourse_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourse',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
