# Generated by Django 5.2.3 on 2025-07-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_teachers_enrolledcourse_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
