# Generated by Django 5.2.3 on 2025-07-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_teachers_cartorderitem_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
