# Generated by Django 5.2.3 on 2025-07-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_teacher_cartorder_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='coupons',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, null=True, to='api.coupon'),
        ),
    ]
