# Generated by Django 5.2.3 on 2025-07-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_cartorder_coupons_cartorder_coupons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantitem',
            old_name='varient_item_id',
            new_name='variant_item_id',
        ),
    ]
