# Generated by Django 5.2.3 on 2025-07-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_varient_item_id_variantitem_variant_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedlesson',
            old_name='varient_item',
            new_name='variant_item',
        ),
    ]
