# Generated by Django 5.2.3 on 2025-06-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp1',
            new_name='otp',
        ),
    ]
